steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
     - '-c'
     - >
       gcloud deploy releases create rel-$(date +%y%m%d-%s)
       --delivery-pipeline=cloud-deploy-helm
       --region=us-central1
