steps:
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
     - '-c'
     - >
       gcloud beta deploy releases create rel-$(date +%y%m%d-%s)
       --delivery-pipeline=cloud-deploy-kus
       --region=us-central1  --images=myapp-image=${_TAG_NAME}
