apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: cloud-deploy-helm
description: main application pipeline
serialPipeline:
 stages:
 - targetId: devtarget
   profiles: 
   - test
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: devtarget
description: development namespace
gke:
 cluster: projects/dc-hughes-anthos-migration/locations/us-central1-c/clusters/dev
