apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: googlepoc
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: myweb
