apiVersion: skaffold/v2beta16
kind: Config
profiles:
- name: test
  deploy:
   helm:
    releases: 
    - name: test-app
      chartPath: helm/project
      namespace: test
      valuesFile:
       - "helm/project/dev-values.yaml"
