apiVersion: skaffold/v2beta16
kind: Config
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - cd/env/dev
  - name: qa
    deploy:
      kustomize:
        paths:
          - cd/env/qa
