apiVersion: skaffold/v2beta26
kind: Config
profiles:
- name: test
  deploy:
   kustmoize:
    paths:
     - cd/env/dev
    hooks:
     before:
      host:
       command: ["sh", "-c", "kubectl", "get", "ns"]
