---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: $(Values.file1.spec.name)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: myapp-image
        imagePullPolicy: Always
        name: myweb
