bases:
  - ../../base


namespace: test
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: myweb
  path: value_var.yaml

configMapGenerator:
- name: j2p9-env-var
  options:
   disableNameSuffixHash: true
  files:
  - /workspace/DSS/config/config.sh
- name: j2p9-config-file
  options: 
   disableNameSuffixHash: true
  files:
  - /workspace/DSS/config/config.sh
  - /workspace/DSS/config/environ.sh
